kind: Deployment
apiVersion: apps/v1
metadata:
  name: memealyzernetwebapp
  labels:
    app.kubernetes.io/name: 'memealyzernetwebapp'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memealyzernetwebapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'memealyzernetwebapp'
        app.kubernetes.io/part-of: 'memealyzer'
    spec:
      containers:
      - name: memealyzernetwebapp
        image: meme721acr.azurecr.io/memealyzernetwebapp:1.0.13
        imagePullPolicy: Always
        env:
        - name: DOTNET_LOGGING__CONSOLE__DISABLECOLORS
          value: 'true'
        - name: ASPNETCORE_URLS
          value: 'http://*'
        - name: PORT
          value: '80'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PORT
          value: '1080'
        - name: SERVICE__MEMEALYZERNETWEBAPP__HOST
          value: 'memealyzernetwebapp'
        - name: SERVICE__MEMEALYZERNETAPI__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETAPI__PORT
          value: '2080'
        - name: SERVICE__MEMEALYZERNETAPI__HOST
          value: 'memealyzernetapi'
        ports:
        - containerPort: 80
...
---
kind: Service
apiVersion: v1
metadata:
  name: memealyzernetwebapp
  labels:
    app.kubernetes.io/name: 'memealyzernetwebapp'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  selector:
    app.kubernetes.io/name: memealyzernetwebapp
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1080
    targetPort: 80
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: memealyzernetapi
  labels:
    app.kubernetes.io/name: 'memealyzernetapi'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memealyzernetapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'memealyzernetapi'
        app.kubernetes.io/part-of: 'memealyzer'
    spec:
      containers:
      - name: memealyzernetapi
        image: meme721acr.azurecr.io/memealyzernetapi:1.0.13
        imagePullPolicy: Always
        env:
        - name: BASENAME
          value: 'meme721'
        - name: LOCATION
          value: 'westus2'
        - name: FAILOVER_LOCATION
          value: 'eastus2'
        - name: DOTENV_FILENAME
          value: '.env'
        - name: FUNCTION_APPS
          value: 'meme721function|src/net/Services/Functions'
        - name: PROVISION_FILE
          value: 'iac/main.bicep'
        - name: PROVISION_TEMPLATE_FILE
          value: '@iac/main.parameters.json'
        - name: TYE_FILE
          value: 'tye.yaml'
        - name: TYE_RUN_ARGS
          value: '--watch --logs console -v debug --tags local'
        - name: TYE_DEPLOY_ARGS
          value: '-v debug --tags cloud'
        - name: TYE_UNDEPLOY_ARGS
          value: '-v debug --tags cloud'
        - name: TYE_DEBUG_ARGS
          value: '--watch --logs console -v debug --tags local --debug memealyzernetqueueservice'
        - name: TYE_GENERATE_ARGS
          value: '-v debug --tags cloud'
        - name: AZURE_CLI_DEBUG
          value: 'false'
        - name: AZURE_CONTAINER_REGISTRY_SERVER
          value: 'meme721acr.azurecr.io'
        - name: ENVSUBS
          value: 'tye.template.yaml|tye.yaml,src/net/WebApp/wwwroot/appsettings.template.json|src/net/WebApp/wwwroot/appsettings.json,iac/main.parameters.template.json|iac/main.parameters.json'
        - name: CONTAINER_TAG
          value: '1.0.13'
        - name: IMAGE_ENDPOINT
          value: 'https://meme-api.herokuapp.com/gimme/wholesomememes'
        - name: DOTNET_LOGGING__CONSOLE__DISABLECOLORS
          value: 'true'
        - name: ASPNETCORE_URLS
          value: 'http://*'
        - name: PORT
          value: '80'
        - name: SERVICE__MEMEALYZERNETAPI__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETAPI__PORT
          value: '2080'
        - name: SERVICE__MEMEALYZERNETAPI__HOST
          value: 'memealyzernetapi'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PORT
          value: '1080'
        - name: SERVICE__MEMEALYZERNETWEBAPP__HOST
          value: 'memealyzernetwebapp'
        ports:
        - containerPort: 80
...
---
kind: Service
apiVersion: v1
metadata:
  name: memealyzernetapi
  labels:
    app.kubernetes.io/name: 'memealyzernetapi'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  selector:
    app.kubernetes.io/name: memealyzernetapi
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 2080
    targetPort: 80
...
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: memealyzernetqueueservice
  labels:
    app.kubernetes.io/name: 'memealyzernetqueueservice'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memealyzernetqueueservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'memealyzernetqueueservice'
        app.kubernetes.io/part-of: 'memealyzer'
    spec:
      containers:
      - name: memealyzernetqueueservice
        image: meme721acr.azurecr.io/memealyzernetqueueservice:1.0.13
        imagePullPolicy: Always
        env:
        - name: BASENAME
          value: 'meme721'
        - name: LOCATION
          value: 'westus2'
        - name: FAILOVER_LOCATION
          value: 'eastus2'
        - name: DOTENV_FILENAME
          value: '.env'
        - name: FUNCTION_APPS
          value: 'meme721function|src/net/Services/Functions'
        - name: PROVISION_FILE
          value: 'iac/main.bicep'
        - name: PROVISION_TEMPLATE_FILE
          value: '@iac/main.parameters.json'
        - name: TYE_FILE
          value: 'tye.yaml'
        - name: TYE_RUN_ARGS
          value: '--watch --logs console -v debug --tags local'
        - name: TYE_DEPLOY_ARGS
          value: '-v debug --tags cloud'
        - name: TYE_UNDEPLOY_ARGS
          value: '-v debug --tags cloud'
        - name: TYE_DEBUG_ARGS
          value: '--watch --logs console -v debug --tags local --debug memealyzernetqueueservice'
        - name: TYE_GENERATE_ARGS
          value: '-v debug --tags cloud'
        - name: AZURE_CLI_DEBUG
          value: 'false'
        - name: AZURE_CONTAINER_REGISTRY_SERVER
          value: 'meme721acr.azurecr.io'
        - name: ENVSUBS
          value: 'tye.template.yaml|tye.yaml,src/net/WebApp/wwwroot/appsettings.template.json|src/net/WebApp/wwwroot/appsettings.json,iac/main.parameters.template.json|iac/main.parameters.json'
        - name: CONTAINER_TAG
          value: '1.0.13'
        - name: IMAGE_ENDPOINT
          value: 'https://meme-api.herokuapp.com/gimme/wholesomememes'
        - name: DOTNET_LOGGING__CONSOLE__DISABLECOLORS
          value: 'true'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETWEBAPP__PORT
          value: '1080'
        - name: SERVICE__MEMEALYZERNETWEBAPP__HOST
          value: 'memealyzernetwebapp'
        - name: SERVICE__MEMEALYZERNETAPI__PROTOCOL
          value: 'http'
        - name: SERVICE__MEMEALYZERNETAPI__PORT
          value: '2080'
        - name: SERVICE__MEMEALYZERNETAPI__HOST
          value: 'memealyzernetapi'
...
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: memealyzernetwebapp
            port:
              number: 1080
        pathType: Prefix
        path: /()(.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(images.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(image.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(config.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(imagehub.*)
...
