name: memealyzer
registry: memealyzerdevacr.azurecr.io
services:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    bindings:
      - name: blob
        port: 10000
        containerPort: 10000
        protocol: http
      - name: queue
        port: 10001
        containerPort: 10001
        protocol: http
    tags:
      - dev
  - name: memealyzernetwebapp
    project: ../../../src/net/WebApp/WebApp.csproj
    bindings:
      - port: 1080
        containerPort: 80
    env_file:
      - ../../../.env
    tags:
      - dev
      - staging
      - prod
  - name: memealyzernetapi
    project: ../../../src/net/Api/Api.csproj
    bindings:
      - port: 2080
        containerPort: 80
    env_file: 
      - ../../../.env
    tags:
      - dev
      - staging
      - prod
  - name: memealyzernetfunction
    azureFunction: ../../../src/net/Services/Functions/
    bindings:
      - port: 3080
        protocol: http
    tags:
      - dev
  - name: memealyzernetqueueservice
    project: ../../../src/net/Services/QueueService/QueueService.csproj
    env_file: 
    - ../../../.env
    tags:
      - dev
      - staging
      - prod

ingress:
  - name: ingressdev
    rules:
      - path: /
        service: memealyzernetwebapp
      - path: /images
        service: memealyzernetapi
        preservePath: true
      - path: /image
        service: memealyzernetapi
        preservePath: true
      - path: /config
        service: memealyzernetapi
        preservePath: true
      - path: /imagehub
        service: memealyzernetapi
        preservePath: true
      - path: /api/negotiate
        service: memealyzernetfunction
        preservePath: true
    tags:
      - dev
  - name: ingress
    rules:
      - path: /
        service: memealyzernetwebapp
      - path: /images
        service: memealyzernetapi
        preservePath: true
      - path: /image
        service: memealyzernetapi
        preservePath: true
      - path: /config
        service: memealyzernetapi
        preservePath: true
      - path: /imagehub
        service: memealyzernetapi
        preservePath: true
    tags:
      - staging
      - prod