on:
  workflow_dispatch:
    branches:
      - cdk
  push:
    branches:
      - cdk
  pull_request:
    branches:
      - cdk
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  BASENAME: memecdk1
  LOCATION: westus2
  FAILOVER_LOCATION: eastus2
  AZURE_FUNCTION_APPS: memecdk1function|src/net/Services/Functions
  CONTAINER_TAG: 1.0.${{ github.run_number }}
  IMAGE_ENDPOINT: https://meme-api.herokuapp.com/gimme/wholesomememes
  DEPLOY_ARGS: -v debug --tags cloud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   

    - name: Checkout
      uses: actions/checkout@v2 
    
    - name: Azure CDK Deploy
      id:   azure-cdk-deploy
      uses: jongio/azure-cdk-action@v1

